src/BadBoysBoating/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using ViewModels;
using Business;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Http;

namespace BadBoysBoating.Controllers
{
    public class AdminController : Controller
    {
        [Authorize(Roles = "admin")]
        public IActionResult Accounts()
        {
            ViewData["StyleSheet"] = "Accounts";
            ViewData["Login"] = CheckCookies();
            AuthorizationService service = new AuthorizationService();
            List<AccountViewModel> accounts = service.GetAllAccounts();
            return View(accounts);
        }

        [Authorize(Roles = "admin")]
        public IActionResult News()
        {
            NewsService service = new NewsService();
            List<NewsCollectionViewModel> news = service.GetAllNews(new PageInfo { PageNumber = 1, PageSize = 100000 });
            ViewData["StyleSheet"] = "News";
            ViewData["Login"] = CheckCookies();
            return View(news);
        }

        public IActionResult AddNews()
        {
            return View();
        }

        public IActionResult EditNews(int id)
        {
            NewsService service = new NewsService();
            NewsViewModel news = service.GetNewsInfo(id);
            return View(news);
        }

        [HttpPost]
        public IActionResult SetLanguage(string culture, string returnUrl)
        {
            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
            );

            return LocalRedirect(returnUrl);
        }

        private string CheckCookies()
        {
            if (User.Identity.Name != null)
            {
                ViewData["Role"] = User.FindFirst(x => x.Type == ClaimsIdentity.DefaultRoleClaimType).Value;
                return User.Identity.Name;
            }
            else
            {
                return "";
            }
        }
    }
}

src/BadBoysBoating/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Business;
using ViewModels;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Http;

namespace BadBoysBoating.Controllers
{
    public class UserController : Controller
    {
        private int account_id;

        [Authorize(Roles = "admin, customer, client")]
        public IActionResult Index(int page_num = 1)
        {
            AuthorizationService a_service = new AuthorizationService();
            AccountViewModel account = a_service.GetAccountInfo(User.Identity.Name);
            if (account.AccountType.Equals("customer"))
            {
                MessageService r_service = new MessageService();
                account.Recalls = r_service.GetInbox(account.Id);
                BoatService b_service = new BoatService();
                account.Boats = b_service.GetUsersBoat(account.Id);

            }
            ViewData["StyleSheet"] = "Profile";
            ViewData["Login"] = CheckCookies();
            return View(account);
        }

        [Authorize(Roles = "customer, client")]
        public IActionResult Recalls(string recalls_type)
        {
            InitializeAccountId();
            List<MessageViewModel> recalls = null;
            switch (recalls_type)
            {
                case "outbox":
                    {
                        MessageService r_service = new MessageService();
                        recalls = null;
                    }
                    break;
                case "inbox":
                    {
                        MessageService r_service = new MessageService();
                        recalls = null;
                    }
                    break;
            }
            return View(recalls);
        }        

        private void InitializeAccountId()
        {
            AuthorizationService service = new AuthorizationService();
            AccountViewModel account = service.GetAccountInfo(User.Identity.Name);
            account_id = account.Id;
        }

        [HttpPost]
        public IActionResult SetLanguage(string culture, string returnUrl)
        {
            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
            );

            return LocalRedirect(returnUrl);
        }

        private string CheckCookies()
        {
            if (User.Identity.Name != null)
            {
                ViewData["Role"] = User.FindFirst(x => x.Type == ClaimsIdentity.DefaultRoleClaimType).Value;
                return User.Identity.Name;
            }
            else
            {
                return "";
            }
        }
    }
}

src/BadBoysBoating/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BadBoysBoating</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/menu.css" />  
        <link rel="stylesheet" href="~/css/content.css" />     
        @switch (ViewData["StyleSheet"].ToString())
        {
            case "Index":
                {
                     <link rel="stylesheet" href="~/css/index.css" />
                } break;
            case "About":
                {
                    <link rel="stylesheet" href="~/css/about.css" />
                } break;
            case "Contact":
                {
                    <link rel="stylesheet" href="~/css/contact.css" />
                } break;
            case "Product":
                {
                    <link rel="stylesheet" href="~/css/probuct.css" />
                } break;
            case "Sale":
                {
                    <link rel="stylesheet" href="~/css/sale.css" />
                } break;
            case "Rent":
                {
                    <link rel="stylesheet" href="~/css/rent.css" />
                } break;
            case "News":
                {
                    <link rel="stylesheet" href="~/css/news.css" />
                } break;
            case "Previews":
                {
                    <link rel="stylesheet" href="~/css/previews.css" />
                }
                break;
            case "Profile":
                {
                    <link rel="stylesheet" href="~/css/profile.css" />
                }
                break;
        }
        <!--link rel="stylesheet" href="~/css/content.css" />
        <link rel="stylesheet" href="~/css/about.css" />
        <link rel="stylesheet" href="~/css/contact.css" />-->
        <script src="~/js/site.js" type="text/javascript"></script>
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.ApplicationInsightsJavaScript(TelemetryConfiguration)
</head>
<body>       
    <div id="side_container">
        <header>
            <div id="logotype">
                <a asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/site_logo.jpg" />
                </a>
            </div>
            <div id="navigation_menu" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (ViewData["Login"].ToString().Length > 0)
                    {
                        @if (!ViewData["Role"].ToString().Equals("admin"))
                        {
                        <li><a asp-area="" asp-controller="Home" asp-action="Index">@Localizer["String1"]</a></li>
                        }
                    }
                    else
                    {
                        <li><a asp-area="" asp-controller="Home" asp-action="Index">@Localizer["String1"]</a></li>
                    }
                    @if (ViewData["Login"].ToString().Length > 0)
                    {
                        <li><a asp-area="" asp-controller="User" asp-action="Index">@Localizer["String16"]</a></li>                       
                    }                                           
                    @if (ViewData["Login"].ToString().Length > 0 && ViewData["Role"].ToString().Equals("admin"))
                    {
                        <li><a asp-area="" asp-controller="Admin" asp-action="Accounts">@Localizer["String17"]</a></li>
                        <li><a asp-area="" asp-controller="Admin" asp-action="News">@Localizer["String2"]</a></li>
                    }
                    else
                    {
                        <li><a asp-area="" asp-controller="News" asp-action="Index">@Localizer["String2"]</a></li>
                        <li class="navbar-collapse collapse">
                            <a id="product_link">@Localizer["String3"]</a>
                            <ul id="product_list" class="nav navbar-nav collapse list">
                                <li><a asp-area="" asp-controller="Boat" asp-action="Sale">@Localizer["String4"]</a></li>
                                <li><a asp-area="" asp-controller="Boat" asp-action="Rent">@Localizer["String5"]</a></li>
                            </ul>
                        </li>
                        <li class="navbar-collapse collapse">
                            <a id="about_link">@Localizer["String6"]</a>
                            <ul id="about_list" class="nav navbar-nav collapse list">
                                <li><a href="~/Home/About#history">@Localizer["String7"]</a></li>
                                <li><a>@Localizer["String8"]</a></li>
                                <li><a>@Localizer["String9"]</a></li>
                                <li><a>@Localizer["String10"]</a></li>
                            </ul>
                        </li>
                        <li><a asp-area="" asp-controller="Home" asp-action="Contact">@Localizer["String11"]</a></li>
                    }                    
                </ul>
            </div>
            <div id="registration_menu" class="navbar-collapse collapse">
                @if (ViewData["Login"].ToString().Length > 0)
                {
                    <a id="logout_button" class="btn btn-primary  my-btn" asp-area="" asp-controller="Account" asp-action="Logout">@Localizer["String12"]</a>
                }
                else
                {
                    <a id="login_button" class="btn btn-primary my-btn" asp-area="" asp-controller="Account" asp-action="LoginAccount">@Localizer["String13"]</a>
                    <a id="register_button" class="btn btn-primary my-btn" asp-area="" asp-controller="Account" asp-action="Register">@Localizer["String14"]</a>
                }               
            </div>
        </header>
        <footer>
            <!--<p>&copy; 2016 Developed by Iundin Alexander and Velichko Michail</p>
                -->
            <div>                
                @await Html.PartialAsync("_SelectLanguagePartial")
            </div>
        </footer>
    </div>     
    <div class="content container body-content text">
        @RenderBody()
        <div class="authors">
            <p>&copy; 2016 @Localizer["String15"]</p>
        </div>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>

src/BadBoysBoating/Views/Shared/_SelectLanguagePartial.cshtml
@using System.Threading.Tasks
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options

@inject IViewLocalizer Localizer
@inject IOptions<RequestLocalizationOptions> LocOptions

@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultureItems = LocOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.DisplayName })
        .ToList();
}

<div title="@Localizer["Request culture provider:"] @requestCulture?.Provider?.GetType().Name">
    <form id="selectLanguage" asp-controller="Home" asp-action="SetLanguage" asp-route-returnUrl="@Context.Request.Path" method="post" role="form">
        <div class="input-group">
            <label class="input-group-addon my-leng" asp-for="@requestCulture.RequestCulture.UICulture.Name">
                @Localizer["String1"]:
            </label>
            <select name="culture" class="form-control" asp-for="@requestCulture.RequestCulture.UICulture.Name" asp-items="cultureItems"></select>
            <span class="input-group-btn">
                <button type="submit" class="btn btn-secondary my-leng">@Localizer["String2"]</button>
            </span>
        </div>
    </form>
</div>  